# Generated by Django 5.1.6 on 2025-04-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('storage_method', models.CharField(choices=[('冷蔵', '冷蔵'), ('冷凍', '冷凍'), ('常温', '常温')], max_length=10)),
            ],
        ),
    ]
