# Generated by Django 5.1.6 on 2025-04-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("week_recipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("recipe_url", models.URLField()),
                ("ingredients", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("is_purchased", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_items",
                        to="week_recipe.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_of", models.DateField(help_text="この週の開始日（月曜日）")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "月曜日"),
                            (1, "火曜日"),
                            (2, "水曜日"),
                            (3, "木曜日"),
                            (4, "金曜日"),
                            (5, "土曜日"),
                            (6, "日曜日"),
                        ]
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_menus",
                        to="week_recipe.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["week_of", "weekday"],
                "unique_together": {("week_of", "weekday")},
            },
        ),
    ]
